apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: {{ .ManagedClusterName }}
  namespace: {{ .ManagedClusterName }}
  labels:
    cloud: {{ .ManagedClusterCloud }}
    region: {{ .ManagedClusterRegion }}
    vendor: {{ .ManagedClusterVendor }}
spec:
  baseDomain: {{ .ManagedClusterBaseDomain }}
  clusterName: {{ .ManagedClusterName }}
  controlPlaneConfig:
    servingCertificates: {}
  installAttemptsLimit: 2
  installed: false
  platform:
{{if (eq .ManagedClusterCloud "aws") }}
    aws:
{{ end }}
{{if (eq .ManagedClusterCloud "azure") }}
    azure:
      baseDomainResourceGroupName: {{ .ManagedClusterBaseDomainRGN }}
{{ end }}
{{if (eq .ManagedClusterCloud "gcp") }}
    gcp:
{{ end }}
{{if (eq .ManagedClusterCloud "baremetal") }}
    baremetal:
      libvirtSSHPrivateKeySecretRef:
        name: {{ .ManagedClusterName }}-ssh-private-key
{{ end }}
      credentialsSecretRef:
        name: {{ .ManagedClusterName }}-creds
      region: {{ .ManagedClusterRegion }}
  provisioning:
    installConfigSecretRef:
      name: {{ .ManagedClusterName }}-install-config
    sshPrivateKeySecretRef:
      name: {{ .ManagedClusterName }}-ssh-private-key
    imageSetRef:
       #quay.io/openshift-release-dev/ocp-release:4.3.28-x86_64
      name: {{ .ManagedClusterImageRefName }}
{{if (eq .ManagedClusterCloud "baremetal") }}
    sshKnownHosts: {{ .SSHKnownHosts }}
{{ end }}
  pullSecretRef:
    name: {{ .ManagedClusterName }}-pull-secret
