apiVersion: v1
metadata:
  name: {{ .ManagedClusterName }}
baseDomain: {{ .ManagedClusterBaseDomain }}
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
  platform:
    baremetal: {}
compute:
- name: worker
  replicas: 2
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineCIDR: 192.168.124.0/24
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  baremetal:
    libvirtURI: {{ .ManagedClusterLibvirtURI }}
    provisioningNetworkCIDR:
    provisioningNetworkInterface: enp1s0
    provisioningBridge: provisioning
    externalBridge: baremetal
    apiVIP:
    ingressVIP:
    bootstrapOSImage: >-
      {{ .ManagedClusterBootstrapOSImage }}
    clusterOSImage: >-
      {{ .ManagedClusterClusterOSImage }}
    hosts: >-
      {{ .Hosts }}
pullSecret: "" # skip, hive will inject based on it's secrets
sshKey: |-
{{ .ManagedClusterSSHPublicKey | indent 4 }}
additionalTrustBundle: |-
{{ .ManagedClusterTrustBundle | indent 4 }}